name: kai_mobile_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.0.6
  rxdart: ^0.24.1
  dio: ^3.0.10
  eva_icons_flutter: ^2.0.1
  shared_preferences: ^0.5.12+2
  flutter_spinkit: ^4.1.2+1
  google_maps_flutter: ^1.0.6
  intl: ^0.16.1
  flutter_linkify: ^4.0.2
  url_launcher: ^5.7.10
  image_picker: ^0.6.3+1
  image_cropper: ^1.2.0
  socket_io_client: ^0.9.12
  day_night_switcher: ^0.1.1+1
  flutter_markdown: ^0.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
   - assets/placeholder.png

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

